- name: Install redis
  ansible.builtin.package:
    name: redis
    state: present

- name: Allow all access to tcp port 6379 for Redis
  community.general.ufw:
    rule: allow
    port: '6379'
    proto: tcp

- name: Allow all access to udp port 6379 for Redis
  community.general.ufw:
    rule: allow
    port: '5379'
    proto: udp
