- name: Allow all access to tcp port 80 for NGINX Proxy
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow all access to udp port 80 for NGINX Proxy
  community.general.ufw:
    rule: allow
    port: '80'
    proto: udp

- name: Allow all access to tcp port 8080 for uWSGI web server
  community.general.ufw:
    rule: allow
    port: '8080'
    proto: tcp

- name: Allow all access to udp port 8080 for uWSGI web server
  community.general.ufw:
    rule: allow
    port: '8080'
    proto: udp

- name: Allow all access to tcp port 8800 for uWSGI datapusher service
  community.general.ufw:
    rule: allow
    port: '8800'
    proto: tcp

- name: Allow all access to udp port 8800 for uWSGI datapusher service
  community.general.ufw:
    rule: allow
    port: '8800'
    proto: udp

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Create ckan nginx site
  ansible.builtin.template:
    src: roles/nginx/templates/ckan.j2
    dest: /etc/nginx/sites-available/ckan
    mode: '0755'

- name: Enable ckan site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/ckan
    dest: /etc/nginx/sites-enabled/ckan
    state: link
  notify:
    - "Restart nginx"

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
