- name: Create ckan app directory
  ansible.builtin.file:
    path: /etc/ckan/default
    state: directory
    mode: '0755'

- name: Create ckan uploads directory
  ansible.builtin.file:
    path: /var/lib/ckan/default
    owner: www-data
    state: directory
    mode: '777' # FIXME Switch ownership and access to ckan https://github.com/ckan/ckan/issues/3676

- name: Create ckan config
  ansible.builtin.template:
    src: roles/ckan/templates/ckan.ini.j2
    dest: /etc/ckan/default/ckan.ini

- name: Create ckan uwsgi script
  ansible.builtin.template:
    src: roles/ckan/templates/wsgi.py.j2
    dest: /etc/ckan/default/wsgi.py

- name: Create ckan uwsgi config
  ansible.builtin.template:
    src: roles/ckan/templates/ckan-uwsgi.ini.j2
    dest: /etc/ckan/default/ckan-uwsgi.ini

- name: Create ckan venv directory
  ansible.builtin.file:
    path: /usr/lib/ckan/default
    state: directory
    mode: '0755'

- name: Create ckan python venv
  ansible.builtin.command:
    cmd: /usr/bin/python3 -m venv /usr/lib/ckan/default
    creates: /usr/lib/ckan/default/bin/activate

# TODO The psycopg2 installation in other locations other than the venv may be redundant.
- name: Install psycopg2 into ckan venv
  ansible.builtin.pip:
    name: psycopg2-binary
    virtualenv: /usr/lib/ckan/default

- name: Install uwsgi into ckan venv
  ansible.builtin.pip:
    name: uwsgi
    virtualenv: /usr/lib/ckan/default

- name: Install ckan
  ansible.builtin.shell: |
    source "/usr/lib/ckan/default/bin/activate"
    pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.10.1#egg=ckan[requirements]'
  args:
    executable: /bin/bash

- name: Initialize ckan database
  ansible.builtin.shell:
    cmd: /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini db init

- name: Set correct privileges to internalization
  ansible.builtin.file:
    path: /usr/lib/ckan/default/src/ckan/ckan/public/base/i18n/
    owner: www-data
    mode: u+rwx
