- name: Create ckan app directory
  ansible.builtin.file:
    path: /etc/ckan/default
    state: directory
    mode: '0755'

- name: Create ckan uploads directory
  ansible.builtin.file:
    path: /var/lib/ckan/default
    owner: www-data
    state: directory
    mode: u+rwx

- name: Check ckan config
  ansible.builtin.stat:
    path: /etc/ckan/default/ckan.ini
  register: ckan_config

- name: Create ckan config
  ansible.builtin.template:
    src: roles/ckan/templates/ckan.ini.j2
    dest: /etc/ckan/default/ckan.ini
    mode: '0755'
  when: "not ckan_config.stat.exists"

- name: Create ckan uwsgi script
  ansible.builtin.template:
    src: roles/ckan/templates/wsgi.py.j2
    dest: /etc/ckan/default/wsgi.py
    mode: '0755'

- name: Create ckan uwsgi config
  ansible.builtin.template:
    src: roles/ckan/templates/ckan-uwsgi.ini.j2
    dest: /etc/ckan/default/ckan-uwsgi.ini
    mode: '0644'

- name: Create ckan venv directory
  ansible.builtin.file:
    path: /usr/lib/ckan/default
    state: directory
    mode: '0755'

- name: Create ckan python venv
  ansible.builtin.command:
    cmd: /usr/bin/python3 -m venv /usr/lib/ckan/default
    creates: /usr/lib/ckan/default/bin/activate

- name: Install psycopg2 into ckan venv
  ansible.builtin.pip:
    name: psycopg2-binary
    virtualenv: /usr/lib/ckan/default

# XLOADER

- name: Install xloader requirements.txt
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ckan/ckanext-xloader/master/requirements.txt
    dest: /tmp/xloader_requirements.txt
    mode: '0644'

- name: Install xloader dependinces
  ansible.builtin.pip:
    requirements: /tmp/xloader_requirements.txt
    virtualenv: /usr/lib/ckan/default

- name: Install xloader depenincies
  ansible.builtin.pip:
    name: requests[security]
    virtualenv: /usr/lib/ckan/default

- name: Install xloader into ckan venv
  ansible.builtin.pip:
    name: ckanext-xloader
    virtualenv: /usr/lib/ckan/default

- name: Install uwsgi into ckan venv
  ansible.builtin.pip:
    name: uwsgi
    virtualenv: /usr/lib/ckan/default

- name: Check ckan installation
  ansible.builtin.stat:
    path: /usr/lib/ckan/default/src/
  register: ckan_installed

- name: Install ckan
  ansible.builtin.shell: |
    source "/usr/lib/ckan/default/bin/activate"
    pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.10.1#egg=ckan[requirements]'
  args:
    executable: /bin/bash

- name: Restart solr
  ansible.builtin.service:
    name: solr
    state: restarted

- name: Initialize ckan database
  ansible.builtin.shell:
    cmd: /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini db init

- name: Set correct privileges to internalization
  ansible.builtin.file:
    path: /usr/lib/ckan/default/src/ckan/ckan/public/base/i18n/
    owner: www-data
    mode: u+rwx
