- name: 'Install ckan'
  hosts: ckan
  become: true

  roles:
    - os
    - firewall
    - java
    - python
    - postgres
    - redis
    - solr
    - ckan
    - supervisord
    # TODO Configure handlers for solr, nginx, and supervisord
    - nginx
