- name: 'Install ckan'
  hosts: ckan
  become: true

  roles:
    - os
    - firewall
    - java
    - python
    - postgres_system
    - postgres_data
    - redis
    - geerlingguy.solr
    - ckan
    - nginx
    - supervisord
