ckan:
  hosts:
    vm:
      ansible_host: "{{ lookup('ansible.builtin.env', 'REMOTE_HOST') }}"
  vars:
    ansible_user: "{{ lookup('ansible.builtin.env', 'REMOTE_USER') }}"
    # Currently only 2.10 is supported
    fqdn: localhost
    ckan_version: 2.10
    postgres_host: localhost
    postgres_password: POSTGRES_PASSWORD
    xloader_api_token: ""
    plugins: xloader datastore
