ckan:
  hosts:
    vm:
      ansible_host: "{{ lookup('ansible.builtin.env', 'REMOTE_HOST') }}"
  vars:
    ansible_user: "{{ lookup('ansible.builtin.env', 'REMOTE_USER') }}"
    # Currently only 2.10 is supported
    fqdn: 192.168.121.254
    ckan_version: 2.10
    postgres_password: POSTGRES_PASSWORD
    plugins: xloader datastore
