- name: Install supervisord
  ansible.builtin.package:
    name: supervisor
    state: present

- name: Create supervisord config directory
  ansible.builtin.file:
    path: /etc/supervisor/conf.d
    state: directory
    mode: '0755'

- name: Create ckan uwsgi supervisord script
  ansible.builtin.template:
    src: roles/supervisord/templates/ckan-uwsgi.conf.j2
    dest: /etc/supervisor/conf.d/ckan-uwsgi.conf
    mode: '0644'

- name: Create ckan worker supervisord script
  ansible.builtin.template:
    src: roles/supervisord/templates/ckan-worker.conf.j2
    dest: /etc/supervisor/conf.d/ckan-worker.conf
    mode: '0644'

- name: Check supervisor status
  ansible.builtin.command:
    cmd: service supervisor status
  register: supervisor_status

- name: Set supervisord configuration 
  ansible.builtin.command:
    cmd: supervisord -c /etc/supervisor/supervisord.conf
  when: "'running' not in supervisor_status.stdout"

- name: Restart supervisord
  ansible.builtin.service:
    name: supervisor
    state: restarted

- name: (supervisorctl) Restart all programs and program groups
  community.general.supervisorctl:
    name: all
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Start supervisord
  ansible.builtin.service:
    name: supervisor
    state: started
