- name: Install ufw
  ansible.builtin.package:
    name: ufw
    state: present

- name: Allow all access to tcp port 80 for NGINX Proxy
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow all access to udp port 80 for NGINX Proxy
  community.general.ufw:
    rule: allow
    port: '80'
    proto: udp

- name: Allow all access to tcp port 8080 for uWSGI web server
  community.general.ufw:
    rule: allow
    port: '8080'
    proto: tcp

- name: Allow all access to udp port 8080 for uWSGI web server
  community.general.ufw:
    rule: allow
    port: '8080'
    proto: udp

- name: Allow all access to tcp port 8800 for uWSGI datapusher service
  community.general.ufw:
    rule: allow
    port: '8800'
    proto: tcp

- name: Allow all access to udp port 8800 for uWSGI datapusher service
  community.general.ufw:
    rule: allow
    port: '8800'
    proto: udp

- name: Allow all access to tcp port 8983 for Apache Solr (See Comment)
# TODO Change access to local subnet for Apache Solr
# Solr should never be exposed publicly in a production site. 
  community.general.ufw:
    rule: allow
    port: '8983'
    proto: tcp

- name: Allow all access to tcp port 8983 for Apache Solr (See Comment)
# TODO Change access to local subnet for Apache Solr
# Solr should never be exposed publicly in a production site. 
  community.general.ufw:
    rule: allow
    port: '8983'
    proto: tcp

- name: Allow all access to tcp port 5432 for PostgreSQL
  community.general.ufw:
    rule: allow
    port: '5432'
    proto: tcp

- name: Allow all access to udp port 5432 for PostgreSQL
# TODO Delete if postgres doesn't use udp sockets
  community.general.ufw:
    rule: allow
    port: '5432'
    proto: udp

- name: Allow all access to tcp port 6379 for Redis
# TODO Delete if redis doesn't use tcp sockets
  community.general.ufw:
    rule: allow
    port: '6379'
    proto: tcp

- name: Allow all access to udp port 6379 for Redis
# TODO Delete if redis doesn't use udp sockets
  community.general.ufw:
    rule: allow
    port: '5379'
    proto: udp

- name: Enable UFW
  community.general.ufw:
    state: enabled