- name: Allow localhost access to tcp port 8983 for Apache Solr
  community.general.ufw:
    rule: allow
    port: '8983'
    proto: tcp
    src: 127.0.0.1

- name: Allow localhost access to tcp port 8983 for Apache Solr
  community.general.ufw:
    rule: allow
    port: '8983'
    proto: tcp
    src: 127.0.0.1

- name: Create /tmp/solr
  ansible.builtin.file:
    path: /tmp/solr
    state: directory
    mode: '0755'

- name: Download Solr Archive
  ansible.builtin.get_url:
    url: https://dlcdn.apache.org/lucene/solr/8.11.2/solr-8.11.2.tgz
    dest: /tmp/solr/solr-8.11.2.tgz
    mode: '0755'

- name: Extract Apache Solr Archive
  ansible.builtin.unarchive:
    src: /tmp/solr/solr-8.11.2.tgz
    dest: /tmp/solr
    remote_src: true

- name: Apache Solr installation check
  ansible.builtin.stat:
    path: /opt/solr
  register: solr

- name: Install Apache Solr
  ansible.builtin.command:
    cmd: /tmp/solr/solr-8.11.2/bin/install_solr_service.sh /tmp/solr/solr-8.11.2.tgz
  when: "not solr.stat.exists"

# TODO Set solr environment variables https://solr.apache.org/guide/6_6/taking-solr-to-production.html#TakingSolrtoProduction-init.dscript

- name: Start Apache Solr
  ansible.builtin.service:
    name: solr
    state: started

- name: Apache Solr core installation check
  ansible.builtin.stat:
    path: /var/solr/data/ckan
  register: ckan_core

- name: Install ckan solr core
  become_user: solr
  vars:
    ansible_ssh_pipelining: true
  ansible.builtin.command:
    cmd: /opt/solr/bin/solr create -c ckan
  when: "not ckan_core.stat.exists"

- name: Install ckan solr schema
  ansible.builtin.template:
    src: roles/solr/templates/schema.xml.j2
    dest: /var/solr/data/ckan/conf/managed-schema
    mode: '0755'
  notify:
    - "Restart solr"
