- name: Create /tmp/solr
  ansible.builtin.file:
    path: /tmp/solr
    state: directory

- name: Download Solr Archive
  ansible.builtin.get_url:
    url: https://dlcdn.apache.org/lucene/solr/8.11.2/solr-8.11.2.tgz
    dest: /tmp/solr/solr-8.11.2.tgz

# FIXME Fix failure to unarchive at this task
# https://github.com/ansible/ansible/issues/35645
- name: Extract Apache Solr Archive
  ansible.builtin.unarchive:
    src: /tmp/solr/solr-8.11.2.tgz
    dest: /tmp/solr
    remote_src: yes

- name: Apache Solr installation check
  stat:
    path: /opt/solr
  register: solr

- name: Install Apache Solr
  when: "not solr.stat.exists"
  ansible.builtin.command:
    cmd: /tmp/solr/solr-8.11.2/bin/install_solr_service.sh /tmp/solr/solr-8.11.2.tgz

- name: Start Apache Solr
  ansible.builtin.service:
    name: solr
    state: started

- name: Apache Solr core installation check
  stat:
    path: /var/solr/data/ckan
  register: ckan_core

- name: Install ckan solr core
  when: "not ckan_core.stat.exists"
  become_user: solr
  vars:
    ansible_ssh_pipelining: true
  ansible.builtin.command:
    cmd: /opt/solr/bin/solr create -c ckan


# FIXME Change Solr schema.xml version to 2.8 with ansible template
- name: Install ckan solr schema
  ansible.builtin.template:
    src: roles/solr/templates/schema.xml.j2
    dest: /var/solr/data/ckan/conf/managed-schema
    # FIXME /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml

- name: Start solr
  ansible.builtin.service:
    name: solr
    state: started