- name: Allow all access to tcp port 5432 for PostgreSQL
  community.general.ufw:
    rule: allow
    port: '5432'
    proto: tcp

- name: Allow all access to udp port 5432 for PostgreSQL
  community.general.ufw:
    rule: allow
    port: '5432'
    proto: udp

- name: Install postgresql
  ansible.builtin.package:
    name: postgresql
    state: present

- name: Install libpq
  ansible.builtin.package:
    name: libpq5
    state: present

- name: Install libpq-dev
  ansible.builtin.package:
    name: libpq-dev
    state: present

- name: Start service postgresql, if not started
  ansible.builtin.systemd:
    name: postgresql
    state: started

# CKAN_DEFAULT

- name: Create ckan_default db
  become_user: postgres
  vars:
  # See: https://github.com/ansible/ansible/issues/16048
    ansible_ssh_pipelining: true
  community.postgresql.postgresql_db:
    name: ckan_default
    encoding: UTF-8

- name: Create ckan_default user
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  community.postgresql.postgresql_user:
    db: ckan_default
    name: ckan_default
    password: "{{ postgres_password }}"

- name: Set ckan_default owner to ckan_default
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  community.postgresql.postgresql_owner:
    db: ckan_default
    new_owner: ckan_default
    obj_name: ckan_default
    obj_type: database

- name: GRANT ALL PRIVILEGES ON DATABASE library TO ckan_default
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  community.postgresql.postgresql_privs:
    db: ckan_default
    privs: ALL
    type: database
    obj: ckan_default
    role: ckan_default

# DATASTORE

- name: Create datastore_default db
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  community.postgresql.postgresql_db:
    name: datastore_default
    encoding: UTF-8

- name: Create datastore_default user
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  community.postgresql.postgresql_user:
    db: datastore_default
    name: datastore_default
    password: "{{ postgres_password }}"

- name: Set datastore_default owner to ckan_default
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  community.postgresql.postgresql_owner:
    db: datastore_default
    new_owner: ckan_default
    obj_name: datastore_default
    obj_type: database

- name: Copy PostgreSQL script to target host
  ansible.builtin.template:
    src: roles/postgres/sql/datastore_default.sql
    dest: /tmp/datastore_default.sql
    owner: postgres
    mode: '0644'

- name: Set permissions on datastore_default
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  community.postgresql.postgresql_script:
    db: datastore_default
    path: /tmp/datastore_default.sql
    # TODO only execute when needed
